[modelling]

models = [
  "LinearRegression",
  "RandomForestRegressor",
  "GradientBoostingRegressor",
]


[modelling.hyperparameters.LinearRegression]
fit_intercept = [true, false]
normalize = [false, true]

[modelling.hyperparameters.RandomForestRegressor]
n_estimators = [50, 100, 200, 300]
max_depth = [5, 10, 15, 20, 25]
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]
random_state = 42

[modelling.hyperparameters.GradientBoostingRegressor]
n_estimators = [100, 200, 300]
learning_rate = [0.01, 0.05, 0.1, 0.2]
max_depth = [3, 5, 7, 9]
subsample = [0.7, 0.8, 0.9, 1.0]
random_state = 42

[feature_selection]
features = [
  "price",       # Price of carseats
  "income",      # Income of the area
  "advertising", # Local advertising budget
  "population",  # Population size in the area
  "age",         # Average age in area
  "education",   # Education level in area
  "shelve_loc",  # Quality of shelving location
  "urban",       # Urban location (yes/no)
  "us",          # US location (yes/no)
  "comp_price",  # Number of competitors
]
target = "sales" # Target variable
