[modelling]

models = [
  "LinearRegression",
  "RandomForestRegressor",
  "GradientBoostingRegressor",
  "LGBMRegressor",
]


[modelling.hyperparameters.LinearRegression]
fit_intercept = [true, false]
normalize = [false, true]

[modelling.hyperparameters.RandomForestRegressor]
n_estimators = [50, 100, 200, 300]
max_depth = [5, 10, 15, 20, 25]
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]
random_state = 42

[modelling.hyperparameters.GradientBoostingRegressor]
n_estimators = [100, 200, 300]
learning_rate = [0.01, 0.05, 0.1, 0.2]
max_depth = [3, 5, 7, 9]
subsample = [0.7, 0.8, 0.9, 1.0]
random_state = 42

[modelling.hyperparameters.LGBMRegressor]
n_estimators = [50, 100, 200, 300]
learning_rate = [0.01, 0.05, 0.1, 0.2]
max_depth = [3, 4, 6, 8]
num_leaves = [20, 31, 50, 80]
subsample = [0.6, 0.7, 0.8, 0.9]
colsample_bytree = [0.6, 0.7, 0.8, 0.9]
reg_alpha = [0, 0.1, 0.5]
reg_lambda = [0, 0.1, 0.5]
random_state = 42

[feature_selection]
features = [
  "Price",       # Price of carseats
  "Income",      # Income of the area
  "Advertising", # Local advertising budget
  "Population",  # Population size in the area
  "Age",         # Average age in area
  "Education",   # Education level in area
  "ShelveLoc",   # Quality of shelving location
  "Urban",       # Urban location (yes/no)
  "US",          # US location (yes/no)
  "Competitors", # Number of competitors
]
target = "Sales" # Target variable
