name: PR Checks
on:
  push:
jobs:
  lint:
    if: |
      ! contains(github.repository, 'data-science-template')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.14"
      - name: Install packages
        shell: bash
        run: |
          uv sync --frozen --all-extras
      - name: Run ruff
        shell: bash
        run: |
          uvx ruff check
  test:
    if: |
      ! contains(github.repository, 'data-science-template')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Install packages
        shell: bash
        run: |
          uv sync --frozen --all-extras
      - name: Pytest
        shell: bash
        run: |
          uv run python -m pytest tests
