name: Build Documentation
on:
  push:
    branches:
      - main
jobs:
  build-docs:
    if: |
      ! contains(github.repository, 'data-science-template') &&
      ! contains(github.event.head_commit.message, 'Initial commit')
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.14"
      - name: Install packages
        shell: bash
        run: |
          uv sync --extra docs --no-dev --frozen
      - name: Build docs
        run: uv run mkdocs gh-deploy --force
